# Default values for docker-cache-registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: enix/docker-cache-registry
  tag: ""

cacheProxyEndpoint:

tugger:
  createMutatingWebhook: true
