# Default values for docker-cache-registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: enix/docker-cache-registry
  tag: ""

proxy:
  hostPort: 7439
  verbosity: 1
  env: []

tugger:
  createMutatingWebhook: true
  rules:
    - pattern: ^jainishshah17/tugger.*
    - pattern: ^enix/docker-cache-registry.*
    - pattern: ^registry.*
    - pattern: (.*)
      replacement: localhost:7439/$1
