apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-cache-registry
  namespace: {{ .Release.Namespace }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-watcher
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: docker-cache-registry-pod-watcher
roleRef:
  kind: ClusterRole
  name: pod-watcher
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: docker-cache-registry
    namespace: {{ .Release.Namespace }}
