apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-registry-deployment
  labels:
    app: cache-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-registry
  template:
    metadata:
      labels:
        app: cache-registry
    spec:
      containers:
        - name: cache-registry
          image: registry
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
            {{- range .Values.proxy.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            {{- if .Values.registry.persistence.enabled }}
            - mountPath: /var/lib/registry
              name: registry
            {{- end }}
      volumes:
        {{- if .Values.registry.persistence.enabled }}
        - name: registry
          persistentVolumeClaim:
            claimName: docker-cache-registry-pvc
        {{- end }}
