kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ default (include "cache-registry.fullname" .) .Values.serviceAccount.name }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  {{- if .Values.psp.create }}
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    verbs:
    - use
    resourceNames:
    - {{ include "cache-registry.fullname" . }}
  {{- end }}
