apiVersion: v1
kind: Service
metadata:
  name: dcr-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
{{- include "cache-registry.controllers-selectorLabels" . | nindent 4 }}
